import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: 'S3 Tools | Secure Browser & Uploader',
    template: '%s | S3 Tools',
  },
  description: 'A client-side secure file browser and uploader for Cloudflare R2 and AWS S3. Manage your buckets without sharing credentials.',
  keywords: ['S3', 'R2', 'Cloudflare', 'AWS', 'File Manager', 'Uploader', 'Privacy'],
  authors: [{ name: 'Fiery Tools' }],
  openGraph: {
    title: 'S3 Tools',
    description: 'Secure client-side browser & uploader for R2 and S3.',
    url: 'https://your-domain.com', // Replace with your actual URL
    siteName: 'S3 Tools',
    locale: 'en_US',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'S3 Tools',
    description: 'Secure client-side browser & uploader for R2 and S3.',
  },
  icons: {
    icon: '/icon', // This matches the route generated by icon.js below
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
